.TH madasulc 1 madasulc\-VERSION
.SH NAME
madasulc client for madasuld
.SH SYNOPSIS
.B madasul
.RB [-p\ port]
.RB [-h\ host]
.RB command
.SH DESCRIPTION
Sends commands to madasuld
.SH OPTIONS
.TP
.B \-p
use port (default: 6666, since 666 is used by doom)
.TP
.B \-h
use host (default: localhost)
.TP
.B command
The Command to send to madasul. See madasuld for list of commands
.SH SEE ALSO
.BR madasuld,madasul
