.TH madasul 1 madasul\-VERSION
.SH NAME
madasul \- a hellish everything player daemon
.SH SYNOPSIS
.B madasul
.RB [ \-... ]
.SH DESCRIPTION
Dinge
.P
See
.B STUFF
i you like
.P
DONGE
.SH OPTIONS
.TP
.B \-...
parameters come
.SH USAGE
.SS Socket commands
.TP
.B cmd1
bla
.BR some cmd 
blub.
.TP
.B cmd2
laber
.SS other
.TP
.B kling
klang
.SH CUSTOMIZATION
config.h
.SH SEE ALSO
.BR interesting stuff
.SH BUGS
DAS GANZE GEHIRN WEGGESLUTSCHT
