#!/bin/sh

cfgfile="$XDG_CONFIG_HOME/madasul/config.h"
if [ -f $cfgfile ]; then
  madasulbin="$XDG_DATA_HOME/madasul/madasul"
  if [ $cfgfile -nt $madasulbin ]; then
    makedir="/tmp/madasul$$"
    mkdir $makedir
    cp -R "MADASULSRC"* $makedir
    cp $cfgfile $makedir
    cd $makedir
    make
    R=$?
    if [ $R -gt 0 ] && [ $R -le 127 ]; then
      notify-send 'madasulm' 'error compiling new madasul'
    else
      notify-send 'madasulm' 'succesfully compiled new madasul'
      mkdir -p "$XDG_DATA_HOME/madasul"
      cp madasul $madasulbin
    fi
    rm -Rf $makedir
  fi
else
  madasulbinb=`which madasul`
fi

madasulbin="$madasulbin 2>&1 >> ~/.local/share/madasul/log"

exec $madasulbin
