.TH madasul 1 madasul\-VERSION
.SH NAME
madasul \- some kind of media daemon
.SH SYNOPSIS
.B madasul
.RB [-p\ port]
.RB [-f\ list]
.SH DESCRIPTION
Madasul gets a list of files on stdin. Madasul itself is way to evil for such
low tasks as playing something, so lesser programs are utilized, wether they
like it or not.
.SH OPTIONS
.TP
.B \-p
use port (default: 6666, since 666 is used by doom)
.TP
.B \-f
load file (default: $XDG_CONFIG_HOME/madasul/list)
.SH USAGE
.SS Socket commands
.TP
.B status
Human readable status
.TP
.B play [num]
Start playing or play track 
.BR num
.TP
.B playpause [num]
Play/Pause or play track 
.BR num
.TP
.B next [num]
Play next or skip 
.BR num 
files
.B prev [num]
Play next or skip 
.BR num 
files backwards
.TP
.B stop
Stop playing
.TP
.B pause
Pause playing
.TP
.B die
Even madasul can die
.TP
.B random
Toggle random
.TP
.B tracklist
List all loaded tracks
.TP
.B setlist
Set a playlist (a comma seperated list of track numbers)
.TP
.B showlist
Show tracks in playlist
.SS File list format
.TP
One tab-seperated line per file, containing file type and path and optionally album, artist, title, date, genre, track number in this exact order.
.SH CUSTOMIZATION
config.h
.SH SEE ALSO
.BR angl,\ mcp,\ mlg
.SH BUGS
DAS GANZE GEHIRN WEGGESLUTSCHT
