#!/bin/bash

extravar() {
    echo "Unknwon Parameter $1"
}

. madasul-bashstuff.sh

if [ -z $cmd ]; then
	echo "Usage: mcp [-p port] [-h host] command"
	echo
	echo "Commands:"
	cmd_help
	echo
else
	echo "$cmd" | socat - tcp-connect:$host:$port 
fi