#!/bin/bash

extravar() {
    echo "Unknwon Parameter $1"
}

. PREFIX/lib/madasul-bashstuff

track=$(madasulc -h $host -p $port showlib '#i: $a - $l - $t' | dmenu -l 30 -i -p "Select Track: " | cut -d ":" -f 1)

if [ ! -z $track ]; then
	madasulc -h $host -p $port play $track
fi